### ISSUE TITLE
How to pause scanner

### ISSUE THREAD

**Issue by rey5137** [dlazaro66/QRCodeReaderView#10]
When I point the camera to an qr-code, it read the code continuously without a pause. Is there anyway to pause it without calling stopPreview(), and continue after I handle the result?

**Comment by dlazaro66** [comment]
You could just ignore the ```java public void onQRCodeRead(String text, PointF[] points) { ``` callback after the first result if you want to continue with the camera On. I don't provide a method to stop the scanner, but it can be easy to code it. I would kindly accept a pull request :smile:

**Comment by dlazaro66** [comment]
I'm closing this because there is another similar issue: https://github.com/dlazaro66/QRCodeReaderView/issues/28
