### ISSUE TITLE
Marshmallow permissions not added

### ISSUE THREAD

**Issue by ibrahim-appgodz** [dlazaro66/QRCodeReaderView#102]
Please **add support for **marshmallow****... so that it makes useful for many persons...
It **doesnot open in marshmallow devices**. Please include it in your library. Thanks for the easy one you had made.

**Comment by dlazaro66** [comment]
This is not a QRCodeReaderView issue since you need to check the Camera permission in runtime before using the view (please check: http://developer.android.com/intl/pt-br/training/permissions/index.html)
