### ISSUE TITLE
Failed to scan when connected to bluetooth

### ISSUE THREAD

**Issue by SamTew** [dlazaro66/QRCodeReaderView#116]
Surprisingly when the app connected to bluetooth, it failed to scan the qr code. Any solution?

**Comment by CaptainCockwash** [comment]
I'm using a bluetooth connection while i'm scanning qr codes, no issues here. Does the QR code just not get recognised?

**Comment by dlazaro66** [comment]
I cannot see why Bluetooth can affect to the scanning process; can you check if that's happening with different devices?
