### ISSUE TITLE
Waiting for nearly 1514 ms, startCamera in the Activity 

### ISSUE THREAD

**Issue by buttonXin** [dlazaro66/QRCodeReaderView#119]
startActivity(new Intent(this, QRCodeActivity.class));

public class QRCodeActivity extends AppCompatActivity implements QRCodeReaderView.OnQRCodeReadListener {
  @Override
    public void onQRCodeRead(String text, PointF[] points) {
        // When code go here ， It has been a 1514 ms
    }
}
xml  
<com.dlazaro66.qrcodereaderview.QRCodeReaderView
        android:id="@+id/qr_two_xing"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

The code stops at 1514ms in the previous activity ，The last to appear camrea ...  
How fast is it displayed?    Is that ok?  Or I don't understand 。

**Comment by dlazaro66** [comment]
> How fast is it displayed?  Is that ok?
Decoding usually takes time, but bootstrapping the camera is also expensive in time so I'd say it's normal

**Comment by buttonXin** [comment]
ok,  think you
