### ISSUE TITLE
QR Code Scanning didn't work

### ISSUE THREAD

**Issue by RobbenGokul** [dlazaro66/QRCodeReaderView#121]
In some phones the qr code scanning didn't work if i enabled the wifi. After I disabled the wifi connection then the qr code scanning works. I need a quick reply for this. Please answer this as soon as possible.

**Comment by dlazaro66** [comment]
I cannot see how WiFi can affect the camera decoding. Please check with more devices and reopen this if you still see a wrong behavior. Thank you
