### ISSUE TITLE
Torch not turning on/off

### ISSUE THREAD

**Issue by tomerpetel** [dlazaro66/QRCodeReaderView#127]
Hi and first of all thanks for this useful library!

I'm trying to get the torch on/off with no success. I followed the example but it still doesn't work. 
After a short debugging I noticed "openCamera" variable is null and that's why the torch doesn't work. 

Any ideas why "openCamera" is null? The rest of the features do work and I can see a camera preview.

**Comment by dlazaro66** [comment]
Can you provide more information? which device are you using?

**Comment by tomerpetel** [comment]
Hi,
Didn't occur after updating the library. Having other issues however but I'll open them in another thread. Thx!
