### ISSUE TITLE
Display blinks the first time

### ISSUE THREAD

**Issue by FernandoFranco** [dlazaro66/QRCodeReaderView#14]
Helo, i used the QRCodeReaderView in a Fragment, and MaterialTabs.
It works, but the display blinks in the first time to create this fragment.

**Comment by dlazaro66** [comment]
Did you test and reproduce it in different devices?

**Comment by FernandoFranco** [comment]
Yes

**Comment by VAdaihiep** [comment]
I have issue too.
I delay init QRCodeReaderView but when QRCodeReaderView init, the screen still blinked.

**Comment by dlazaro66** [comment]
This is related to this issue, so I'm merging this with #7
