### ISSUE TITLE
How to increase scanning area size?

### ISSUE THREAD

**Issue by dikirpl** [dlazaro66/QRCodeReaderView#16]
Hi! this is great library and i love that

but How to increase scanning area size?

i've searched and found the best solution is like this:
http://stackoverflow.com/questions/20398419/how-to-increase-scanning-area-size-in-zxing

and i noticed you used modify or different version of zxing library.

Any hints to to adjust scanning area size that scale out  with this library?

i've tried to set the width "<com.dlazaro66.qrcodereaderview.QRCodeReaderView" on the layout.xml then the camera view not scale out image correctly

Please advise and i appreciate for your help, thanks mate :)

**Comment by dlazaro66** [comment]
Hi!
The current scanning area is all the camera preview. I removed that area restriction you see in the stackoverflow post. Did you try the example project in this repository?

**Comment by dikirpl** [comment]
Hi Sorry i think i post wrong question  but that's not what i mean,

Yes already try the example project and it's great

Let me ask describe my issue once again,

I tried the example project and want to resize width and height of the camera preview smaller and found the image on the camera preview won't scale out properly, here is the screenshot of my issue:
https://www.dropbox.com/s/exyof5w9evi1b2b/2015-04-27%2012.42.49.jpg?dl=0

And this what i expected, the screenshot comes from blackberry messenger app,
https://www.dropbox.com/s/s6ymn3tgf39xu91/2015-04-27%2012.44.44.jpg?dl=0

Any hints to make it happen?

Once again sorry for the confusing 

Many thanks for your help :)

**Comment by dlazaro66** [comment]
Ok. Sorry but If you set a custom size to the QRCodeReaderView, camera preview will scale as you can see in your first picture. To achieve a behavior like that, maybe you can try to "overlap" or hide the full size camera preview with an opaque view over it, or something like that.
Anyway, as this is not an issue for the library itself, I'm closing it.
