### ISSUE TITLE
Constant GC usage, GC_FOR_ALLOC every 100ms

### ISSUE THREAD

**Issue by dimitrovskif** [dlazaro66/QRCodeReaderView#17]
Device: Galaxy S3
Android: 4.4
Lib version: latest

----

It seems that every 100ms this lib allocates 1876K that Android tries to free. That causes a small FPS drop. Could it be the camera frame (`BinaryBitmap` and `PlanarYUVLuminanceSource`)?

Here's my logcat:
```
04-28 21:40:25.845  13428-13428/com.filip.mojdab D/dalvikvm﹕ GC_FOR_ALLOC freed 1876K, 26% free 19106K/25540K, paused 11ms, total 11ms
04-28 21:40:25.930  13428-13428/com.filip.mojdab D/dalvikvm﹕ GC_FOR_ALLOC freed 1876K, 26% free 19106K/25540K, paused 14ms, total 14ms
04-28 21:40:26.020  13428-13428/com.filip.mojdab D/dalvikvm﹕ GC_FOR_ALLOC freed 1876K, 26% free 19106K/25540K, paused 13ms, total 13ms
04-28 21:40:26.090  13428-13428/com.filip.mojdab D/dalvikvm﹕ GC_FOR_ALLOC freed 1876K, 26% free 19106K/25540K, paused 13ms, total 13ms
04-28 21:40:26.160  13428-13428/com.filip.mojdab D/dalvikvm﹕ GC_FOR_ALLOC freed 1876K, 26% free 19106K/25540K, paused 11ms, total 11ms
04-28 21:40:26.250  13428-13428/com.filip.mojdab D/dalvikvm﹕ GC_FOR_ALLOC freed 1876K, 26% free 19106K/25540K, paused 17ms, total 17ms
..........
```

**Comment by dimitrovskif** [comment]
I don't have git on this machine, but I propose a fix by changing `QRCodeReaderView.java`:

    private int frameCount = 0;
    private static final int SKIP_FRAMES = 3; // will detect 1/3 frames; minimum is 2
    @Override
    public void onPreviewFrame(byte[] data, Camera camera) {
        frameCount++;
        frameCount = frameCount % SKIP_FRAMES;
        if(frameCount != 0){ return; }
        ...

**Comment by dlazaro66** [comment]
This is fixed now since we're doing the decoding process in background. please update to the latest library version.
