### ISSUE TITLE
 import android.hardware.Camera is Deprecated

### ISSUE THREAD

**Issue by yuddis** [dlazaro66/QRCodeReaderView#18]
Hello, i use this lib in my project and i found that now Camera is deprecated. Could you please update this awesome lib using new Camera Lib ? I really appreaciate if you would do that.

Thank You
sorry english is not my native

**Comment by dlazaro66** [comment]
Hi!
I noticed that, I will take a look to the new api and try to migrate if possible. Anyway I will accept a pull request if you do something with this.

**Comment by dlazaro66** [comment]
https://developer.android.com/reference/android/hardware/camera2/package-summary.html

**Comment by dlazaro66** [comment]
Even camera2 provides a lot of new functionalities, at the moment I think it doesn't worth do the migration. For example, you can see this SO thread, talking about this: http://stackoverflow.com/a/28417458
