### ISSUE TITLE
can not detect Code 128

### ISSUE THREAD

**Issue by skzinzuwadia** [dlazaro66/QRCodeReaderView#19]
Hi,
Thanks for nice library
 i have found it can not detect code 128.
http://www.adams1.com/gif/128pix1.gif

if possible please write down steps, how to add support into this lib.

Thank you

**Comment by dlazaro66** [comment]
Hi!
I'm sorry but this project is only adapted for QR codes, as I'm only using the QRCodeReader part of ZXING project (https://github.com/zxing/zxing). The original project is ready to scan other types of codes, including 128, so I recommend you to take a look at ZXING project and try to adapt it on your needs.
