### ISSUE TITLE
barcode can not recognized?

### ISSUE THREAD

**Issue by weizai** [dlazaro66/QRCodeReaderView#20]
2-dimensional bar code can be recognized very fast, however, barcode could not be..  is there anything  wrong?

**Comment by dlazaro66** [comment]
Hi!
I'm sorry but this project is only adapted for QR codes, as I'm only using the QRCodeReader part of ZXING project (https://github.com/zxing/zxing). The original project is ready to scan other types of codes, including barcodes, so I recommend you to take a look at ZXING project and try to adapt it on your needs.
