### ISSUE TITLE
Java Source Code Location

### ISSUE THREAD

**Issue by cgarciae** [dlazaro66/QRCodeReaderView#21]
Hi, noob question: why the main java code is in a separate project? It seems to compile alright (I don't understand why) but I makes harder to inspect you code. To properly get help from both projects I have to open them in separate windows, which makes things harder. Is there an easier way? Shall I try copying the files to one project?

Thanks

**Comment by dlazaro66** [comment]
Hi, 
There is one project for the library itself,  and another with a sample project using that library. 
If you're using Android Studio,  I strongly recommend you to get the QRCodeReaderView library via Gradle dependency.
