### ISSUE TITLE
AUTO_FOCUS_INTERVAL_MS

### ISSUE THREAD

**Issue by Jakevin** [dlazaro66/QRCodeReaderView#23]
Hi @dlazaro66 

I find Zxing AUTO_FOCUS_INTERVAL_MS is 2000L (2s)

but this project AUTO_FOCUS_INTERVAL_MS setting 5000L (5s).

Can create a function to setting this value?

Thx

**Comment by benoffi7** [comment]
Any news? Thanks!

**Comment by gbazilio** [comment]
+1

**Comment by felipepetrin** [comment]
+1

**Comment by gbazilio** [comment]
@dlazaro66 , we have a local fixing for this. Are you considering a pull request?

**Comment by dlazaro66** [comment]
@gbazilio sure! anyway I'm planning improvements for this library soon
