### ISSUE TITLE
AppCompat

### ISSUE THREAD

**Issue by andras-gerendas** [dlazaro66/QRCodeReaderView#25]
This library is incompatible with the AppCompat theme (and android-support library) because it has a styles.xml which redefines the support library's theme. (Theme.Light and Holo later) You are strongly discouraged to use a styles.xml in a library project because of this.

**Comment by Overvenus** [comment]
In android studio, add dependency to `build.gradle`
```
repositories {
    mavenCentral()
}
dependencies {
    compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0'
}
```

In Eclipse, I put two .jar files to libs
![solu](https://cloud.githubusercontent.com/assets/2150711/8953314/fd2d945a-360f-11e5-8d3f-1887b629725b.png)

**Comment by carlosnavas91** [comment]
when I compile it throws the error message about the java returning with non-zero result
