### ISSUE TITLE
Some devices couldn't read QR

### ISSUE THREAD

**Issue by johnzheng00** [dlazaro66/QRCodeReaderView#27]
I don't know why

**Comment by dlazaro66** [comment]
Can you provide more information about this?

**Comment by cygenb0ck** [comment]
just tested the demo app on 
Samsung Galaxy S3 GT-I9305 Android 4.4.4 - cannot detect qr code
Samsung Xcover 3 SM-G388F Android 4.4.4 - cannot detect qr code
and a
Oneplus two Android 5.1.1 - here i can detect a qr code
