### ISSUE TITLE
How to stop the reading function at a certain point

### ISSUE THREAD

**Issue by nologinatgit** [dlazaro66/QRCodeReaderView#28]
When I open the Activity that has the reader view, it reads the code and jumps to onQRCodeRead. How can I stop it from keep reading it? I already used this code but this does not stop the reading only the camera preview:

<pre>
 public void onQRCodeRead(String s, PointF[] pointFs)
  {
    myTextView.setText("QR code: "+s);
    mydecoderview.getCameraManager().stopPreview();    
  }
</pre>

**Comment by nielsswinkels** [comment]
Maybe you could add your own boolean isScanning, turn that to false, and when it is false, do nothing in the onQRCodeRead() ?

**Comment by dlazaro66** [comment]
This is fixed, but not released yet. Will be available in the next version.

**Comment by chitrey** [comment]
@dlazaro66 when will it be released? Please release it soon. Greatly appreciated. :+1:
