### ISSUE TITLE
onQRCodeRead() run twice when scanned a QRcode

### ISSUE THREAD

**Issue by LvWind** [dlazaro66/QRCodeReaderView#29]
@Override
    public void onQRCodeRead(String text, PointF[] points) {
        Log.d("TEST","onQRCodeRead");
    }

log shows:
10-15 10:36:10.936 10117-10117/[package] D/TEST: onQRCodeRead
10-15 10:36:11.113 10117-10117/[package] D/TEST: onQRCodeRead

**Comment by btcontract** [comment]
Can confirm this behavior on Xiaomi MI4

**Comment by dlazaro66** [comment]
onQRCodeRead will be called every time a QRcode is detected. Are you using the example project in this repository?

**Comment by LvWind** [comment]
@dlazaro66 It seems camera didn't release immediately when a QRcode is detected. It recognized the last frame of camera view and decode it.

**Comment by dmsherazi** [comment]
I am having similar issue. solved somehow after using this code it would read QR Code multiple times.

```   @Override
    public void onQRCodeRead(String text, PointF[] points) {
        //myTextView.setText(text);
        utils._sendErrorLog(text);
        finish();
        utils._startActivity(this,MainActivity.class);
    }
```

**Comment by hafsalrahman** [comment]
@dmsherazi , do you have any workaround for the mentioned issue?

**Comment by dmsherazi** [comment]
Try it like this

```` public void onQRCodeRead(String text, PointF[] points) {
        //myTextView.setText(text);
        finish();
        utils._startActivity(this,MainActivity.class);
    }````


Once a QR code is read use   `finish();`

**Comment by milanPansuriya** [comment]
i had same problem 
I had put counter for that

**Comment by chitrey** [comment]
@milanPansuriya : Could you please share your solution here. I am facing the same problem

**Comment by chitrey** [comment]
@dmsherazi : Your solution still scans the qr multiple time. I need to start an new activity but again have to navigate to the activity where i have to scan another qr code. if i call finish i can't use the onBackPressed method. Do you have any solution for this?

**Comment by milanPansuriya** [comment]
Use this Kind of  Logic

@Override
public void onQRCodeRead(String text, PointF[] points) {

    if (text.length() > 0) {
        String urlPart = text.substring(0, text.lastIndexOf("/") + 1);
        Log.v("SCANNNNNN", "" + text);
        try {
            // .getCameraManager().getCamera().;
            URL url1 = new URL(urlPart);
            URL url2 = new URL(Utils.VALID_URL);
            if (url1.equals(url2)) {
                code = text.substring(text.lastIndexOf("/") + 1);
                counter++;
                if (counter == 1) {
                    scanUrl = text;
                    //  new getScanResponce().execute();
                    Intent intent = new Intent();
                    // intent.putExtra("privacy", privacy1);
                    intent.putExtra("code", code);
                    intent.putExtra("text", text);
                    setResult(20, intent);
                    finish();
                    Utils.cameraNull = 0;
                    Log.v("cameraNullonQRCodeRead", "onQRCodeRead" +
Utils.cameraNull);
                }
            } else {
                counter++;

                Log.v("text", "1onQRCodeRead" + text);
                if (counter == 1) {
                    Log.v("text", "onQRCodeRead" + text);
                    Intent intent = new Intent();
                    intent.putExtra("code", code);
                    intent.putExtra("text", text);
                    Log.v("Text", text + "  1text ");
                    setResult(20, intent);
                    finish();
                    counter = 0;

                    //showDialog("" + text);
                }
            }
        } catch (MalformedURLException e) {
            Intent intent = new Intent();
            intent.putExtra("code", code);
            intent.putExtra("text", text);
            Log.v("Text", text + "  1text ");
            setResult(20, intent);
            finish();
            e.printStackTrace();
        }
    }
}


*MILAN PANSURIYA*

**Comment by dlazaro66** [comment]
onQRCodeRead will be called every time a QRcode is detected, so this is not an issue. You can add your own logic to stop camera or finish the reader activity inside the `public void onQRCodeRead(String text, PointF[] points) {` callback the first time a QR is read.

**Comment by chitrey** [comment]
@dlazaro66 : Could you please provide with some logic. I can't seem to get around this problem.

**Comment by Base2526** [comment]
solved create check active is open 
public void onQRCodeRead(String text, PointF[] points) { 
   if(!QRCodeResultActivity.active){
        // call first only
   }
}


class QRCodeResultActivity extends Activity {
     static boolean active = false;

      @Override
      public void onStart() {
         super.onStart();
         active = true;
      } 

      @Override
      public void onStop() {
         super.onStop();
         active = false;
      }
}

**Comment by fulviol** [comment]
Also with the command finish() the problem continue
