### ISSUE TITLE
How to Run this program and what should i need to run this program..

### ISSUE THREAD

**Issue by prensV30** [dlazaro66/QRCodeReaderView#32]
This is my first post.... im a newbie here
Could anybody please tell me what should i do to run this program...
what should i need to run this program... should i need some applications to make it run?
if yes what is it..?

Thanks in advance Guys....
I would really appreciate your help...
sorry i really dont know what to do but i want to learn...

**Comment by dlazaro66** [comment]
Hello @prensV30 
I'm glad you found this repo and want to learn, however this is not the place for it.

I don't know your programming knowledge, assuming you know how to code, If you're interested in Android development and understand how this works, I strongly recommend you to check this links:
* http://developer.android.com/intl/es/training/basics/firstapp/index.html
* https://www.udacity.com/course/android-development-for-beginners--ud837
* http://lifehacker.com/i-want-to-write-android-apps-where-do-i-start-1643818268
Also, if you're willing to pay to a course, I think this can be great:
* https://www.udacity.com/course/android-developer-nanodegree--nd801
Anyway, download the development tools and try it yourself is my best advice. 

Finally, if you don't know how to code, or you only want a QR decoder for your Android phone, I recommend you to download this one from Google Play: https://play.google.com/store/apps/details?id=com.google.zxing.client.android

David.

**Comment by prensV30** [comment]
@dlazaro66  Thank you for your suggestions. I'll try it.
