### ISSUE TITLE
Duplicate zip Entry

### ISSUE THREAD

**Issue by DineshNandhagopal** [dlazaro66/QRCodeReaderView#33]
Whenever added project containg 'QRCoderView', the error occurs
>"Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/dlazaro66/qrcodereaderview/QRCodeReaderView$OnQRCodeReadListener.class.".

Please help me to know what is it

**Comment by kalvian1060** [comment]
how to fix it?
