### ISSUE TITLE
Reverse QR Camera

### ISSUE THREAD

**Issue by slizana** [dlazaro66/QRCodeReaderView#34]
Hello, I have made an application based on your code and the scanner is turned 180 degrees, i tried to change rotation in mCameraManager.getCamera().setDisplayOrientation(90) but doesnt work, throws nullpointerexception in CameraManager.

¿What can i do?

PD: My phone is Nexus 5x

Regards

**Comment by vlntdds** [comment]
Same issue, nexus 5x too.

**Comment by vlntdds** [comment]
I've submited a pull request, it fixed the behavior on my nexus 5x
https://github.com/dlazaro66/QRCodeReaderView/pull/35

**Comment by skatset** [comment]
I have same problem. @dlazaro66 , please merge this pull request

**Comment by dlazaro66** [comment]
Thanks all for your contributions, and sorry for the delayed response; I'm merging this right now and uploading a new version to jcenter asap, meanwhile you can download the last commit using jetpack for example :)
