### ISSUE TITLE
Camera crashes on some devices: java.lang.RuntimeException: startPreview failed

### ISSUE THREAD

**Issue by JoeKaldas** [dlazaro66/QRCodeReaderView#43]
My app crashes on some devices giving me  java.lang.RuntimeException: startPreview failed error
in "Camera Manager" class in line 138 "theCamera.startPreview();"

It works fine on some devices, Samsung S6, HTC One M8 with versions 5.1 and 6,0.

However it crashes on Samsung S3 with version 4.3 along with other devices

**Comment by sintret** [comment]
E/com.dlazaro66.qrcodereaderview.QRCodeReaderView: Exception: startPreview failed

**Comment by dlazaro66** [comment]
Can you provide more informtion about this?

**Comment by sintret** [comment]
it is already fixed now. maybe my phone device have no camera.

**Comment by sahityakumarsuman** [comment]
Did anyone get correct response how this can be avoid so crash can be stopped.
