### ISSUE TITLE
QRView activity display for 2 secs and close signalling method for QRImageNotFound

### ISSUE THREAD

**Issue by arashifunsho** [dlazaro66/QRCodeReaderView#48]
I implemented this but whenever i try to scan a QR, the view comes up for a second or two and then closes. When I log.d the methods ot QRCodeReaderView, it shows that method onQRImageNotFound was aalways called immediately. Please help

**Comment by dlazaro66** [comment]
Please can you provide further details about this?

**Comment by dlazaro66** [comment]
Please re-open this if you can provide  further details.

**Comment by arashifunsho** [comment]
Sorry bro, thought I replied the mail I got from github. I had to remove the onQRCodeNotFound method and it worked just fine. Used it for 3 projects now.. ;)
