### ISSUE TITLE
How to display a Scanning indicator? 

### ISSUE THREAD

**Issue by souravmitra15** [dlazaro66/QRCodeReaderView#49]
HI all, the library is quite great. But just asking something, is it possible to show a scanning indicator while scanning the QR-code? Like show a ray scan kind of while the camera scans the code. 
Is yes, please tell me something about the procedure.
Thanks.

**Comment by dlazaro66** [comment]
You can checkout the sample, there's something like that already implemented. Anyway, you can add your custom view or your layouts over the camera preview.
