### ISSUE TITLE
How to show flash light?

### ISSUE THREAD

**Issue by SmartDroidDeveloper** [dlazaro66/QRCodeReaderView#50]
Hello David Lázaro Esparcia,

I am using your library for QR Code scanning functionality. I want flash light functionality too. Please help me how can I do this with your library? Hoping for favorable response.

Thanks .

**Comment by chitrey** [comment]
I was wondering about the same thing. I have been stuck in this for 2 days. Could you please let us know if this can be done using your library? Thanks. A quick response would be much appreciated David. :)

**Comment by dlazaro66** [comment]
At the moment, this is not possible using this library. You can check this link and try to do something like that http://stackoverflow.com/questions/6068803/how-to-turn-on-camera-flash-light-programmatically-in-android
However, this can be an enhancement for the future.

**Comment by dlazaro66** [comment]
This is fixed, but not released yet. Will be available in the next version.
