### ISSUE TITLE
Can not find setBackCamera method

### ISSUE THREAD

**Issue by athysirus** [dlazaro66/QRCodeReaderView#73]
Hi!

I can not find setBackCamera method in version 2.0.0, so how I use camera in this project?

Manifest:
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />

**Comment by dlazaro66** [comment]
You need to upgrade to veraion 2.0.1. It's now public released in jCenter and MavenCentral
