### ISSUE TITLE
java.lang.RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by hypeapps** [dlazaro66/QRCodeReaderView#76]
Hello, amazing library. I used QrcodeReaderView in my app: 
[Endoscope GitHub](https://github.com/hypeapps/Endoscope).

On my android 5.0 Huawe p8 lite and Lg L fino 4.4 everything works fine. But i get many issues and crash report about this. This appears only on 6.0 and 7.0 android.

The realted: [ISSUE](https://github.com/hypeapps/Endoscope/issues/6)

QrCodeReaderView implementation in Endoscope: [Link to github](https://github.com/hypeapps/Endoscope/blob/master/app/src/main/java/pl/hypeapp/Fragments/endoscope/QrCodeScannerFragment.java)
Error Message:
```
java.lang.RuntimeException: Fail to connect to camera service
	at android.hardware.Camera.<init>(Camera.java:511)
	at android.hardware.Camera.open(Camera.java:353)
	at com.google.zxing.client.android.camera.open.GingerbreadOpenCameraInterface.open(GingerbreadOpenCameraInterface.java:57)
	at com.google.zxing.client.android.camera.open.CameraManager.openDriver(CameraManager.java:77)
	at com.dlazaro66.qrcodereaderview.QRCodeReaderView.surfaceCreated(QRCodeReaderView.java:110)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:582)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by dlazaro66** [comment]
this is not a QRCodeReaderView issue, since you need to check the Camera permission in runtime before using the view (please check: http://developer.android.com/intl/pt-br/training/permissions/index.html)

You can check the sample project, and see how we implemented the permission request before start the camera preview.

**Comment by hypeapps** [comment]
@dlazaro66 thank you! I added request permission and everything works ok on emulator.

**Comment by juanlabrador** [comment]
I have the same problem...

Change the class exception here!


>   @Override public void surfaceCreated(SurfaceHolder holder) {
>         Log.d(TAG, "surfaceCreated");
> 
>         try {
>             // Indicate camera, our View dimensions
>             mCameraManager.openDriver(holder, this.getWidth(), this.getHeight());
>         } catch (Exception e) {         <------------------------------------------------------  before IOException
>             Log.w(TAG, "Can not openDriver: " + e.getMessage());
>             mCameraManager.closeDriver();
>         }
> 
>         try {
>             mQRCodeReader = new QRCodeReader();
>             mCameraManager.startPreview();
>         } catch (Exception e) {
>             Log.e(TAG, "Exception: " + e.getMessage());
>             mCameraManager.closeDriver();
>         }
>     }

**Comment by saidnawab** [comment]
hello dears i use this code to make a flash light with strobe mode but it not working for me 



package com.example.saidnawab.flashlight;

import android.content.DialogInterface;
import android.content.pm.PackageManager;
import android.hardware.Camera;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageButton;
import android.widget.SeekBar;
import android.os.AsyncTask;

import java.security.Policy;

import static android.R.id.progress;

public class MainActivity extends AppCompatActivity {
    SeekBar seekBar;
    ImageButton imageButton;
    Camera camera;
    Camera.Parameters parameters;
    boolean isflash = false;
    boolean isOn = false;



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        imageButton = (ImageButton) findViewById(R.id.imageButton);
        if (getApplicationContext().getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_FLASH)) {
            camera = Camera.open();
            parameters = camera.getParameters();
            isflash = true;
        }


        imageButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (isflash) {
                    if (!isOn) {
                        imageButton.setImageResource(R.drawable.on);
                        parameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
                        camera.setParameters(parameters);
                        camera.startPreview();
                        isOn = true;
                    } else {
                        imageButton.setImageResource(R.drawable.off);
                        parameters.setFlashMode(Camera.Parameters.FLASH_MODE_OFF);
                        camera.setParameters(parameters);
                        camera.stopPreview();
                        isOn = false;

                    }

                } else {
                    AlertDialog.Builder builder = new AlertDialog.Builder(MainActivity.this);
                    builder.setTitle("Error.........");
                    builder.setMessage("Flashlight is not Available on this device.....");
                    builder.setPositiveButton("ok", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int i) {
                            dialog.dismiss();
                            finish();
                        }
                    });
                    AlertDialog alertDialog = builder.create();
                    alertDialog.show();
                }
            }
        });
        seekBar.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

            }
        });
    }
    private class asynctask extends AsyncTask<String,Camera.Parameters,Void> {
        @Override
        protected Void doInBackground(String... params) {
           int i=0;
            synchronized (this){
                while (i<10){
                    try{
                        wait(1000);
                        i++;
                    }
                    catch (Exception e){
                        e.printStackTrace();
                    }
                }
            }
            return null;
        }

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
        }

        @Override
        protected void onProgressUpdate(Camera.Parameters... values) {
            super.onProgressUpdate(values);
        }
    }

}

**Comment by neonwarge04** [comment]
I am not even running on Android 6 and this even happens on Android 5. When closing my activity with QR scanner, this crashes.

**Comment by TugbaGonultas** [comment]
I am not using 6.0 but I take same error. I tried onResume and onPause method. But same error continue. Also my app is crashes @neonwarge04 similary. I am using Android 4.4. 
Does anyone have an idea?

**Comment by NilaxSpaceo** [comment]
I am also facing same issue in Android 5.0. Does anyone have solution regarding this?
