### ISSUE TITLE
Add this project to maven central

### ISSUE THREAD

**Issue by ajma** [dlazaro66/QRCodeReaderView#8]

**Comment by dlazaro66** [comment]
Hi!

This project is now available to download from JCenter repository, so if you're using Android Studio, as JCenter is now the default repository you should be able to get this library via Gradle dependency. 
Anyway, I'm trying to sync with Maven Central too.

Thanks!

**Comment by dlazaro66** [comment]
version 2.0.1 of this library is now available in both jCenter and maven central respositories.

**Comment by dlazaro66** [comment]
version 2.0.1 of this library is now available in both jCenter and maven central. From now on I'll upload and sync the releases with those two repositories http://search.maven.org/#artifactdetails%7Ccom.dlazaro66.qrcodereaderview%7Cqrcodereaderview%7C2.0.1%7Caar
