### ISSUE TITLE
How to enable FlashLight ?

### ISSUE THREAD

**Issue by ameerhamza6733** [dlazaro66/QRCodeReaderView#83]
i try to enble the flah light , witch mathod should i call to enable the flash light, i try to call 
  mydecoderview.setTorchEnabled(true); but it not working

**Comment by dlazaro66** [comment]
you should call `mydecoderview.setTorchEnabled(true)` . Did it work finally?

**Comment by surajsahijwani** [comment]
I am not able to turn on flashlight in this library. I used mydecoderview.setTorchEnabled(true) but still there is no option anywhere on the screen to turn ON flashlight. I also tried using third party flashlight code but in that case QR scanner stops working. Please let me know how to give an extra button to turn on flash and how to set a call on that button
