### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by kodladykiran** [dlazaro66/QRCodeReaderView#9]
Hi. thanks for the excellent library.
I need one help.
I need the text value which is being read in the following method in a Activity(CaptureActivity) which is before DecoderActivity.

 @Override
    public void onQRCodeRead(String text, PointF[] points) {
        myTextView.setText(text);
    }
How can I get this value in CaptureActivity ? Though it might be not specific to this library, but your help would be highly appreciated.

**Comment by dlazaro66** [comment]
I don't think this can be considered as an issue for the library, so I'm closing it. If you need help you can checkout the sample project and search how to pass information between Activities forward and backward (Intents and setResult() )

**Comment by kodladykiran** [comment]
Thanks David.
I was able to find solution. but forgot to update it. my apologies.

Thanks,
Kiran
