### ISSUE TITLE
Time between reading

### ISSUE THREAD

**Issue by victorblq** [dlazaro66/QRCodeReaderView#90]
My application send a Toast when the code (read by the QRCodeReader) doesn't exists, but the reader is always enabled, it read the code many times and send a lot of Toasts, how can I configure it to read a code and "wait" some time to read again? I tried with sleep from java.concurrent.TimeUnit but then the Toast isn't shown.

**Comment by dlazaro66** [comment]
sorry, you should NOT sleep the thread to delay the Toast to appear.
Instead, you should manage your logic and desired behavior with the help of this method :
```
// Use this function to enable/disable decoding
        mydecoderview.setQRDecodingEnabled(true);
```
You can for example: Start Decoding - Receive the result callback - Stop decoding - show the Toast - wait for a while - Start decoding again.
